// File automatically generated by TheMill
// Do not manually update this file
import 'vite/modulepreload-polyfill'
import { hydrate } from 'TheMill/hydration'

// Import the generated route tree
import { routeTree } from './routeTree.gen'

hydrate(routeTree)
