// File automatically generated by TheMill
// Do not manually update this file
import { serverSideRendering } from 'TheMill/ssr'

import { routeTree } from './routeTree.gen'

export const renderFn = serverSideRendering(routeTree)
